// ============================================================
//  MaoThink – Question Bank
//  QUESTION_POOL   – regular questions (points: 10) drawn randomly for levels 1-40
//  HARD_QUESTION_POOL – 100+ difficult questions (points: 20); 10 are randomly
//                       selected each game for the final difficult round (levels 41-50)
// ============================================================

const GAME_QUESTION_COUNT = 50;

const QUESTION_POOL = [
  // ── GAME 1 (Questions 1–39) ──────────────────────────────
  { category: "🌍 Geography", question: "What is the capital of Canada?", choices: ["Ottawa", "Toronto", "Vancouver", "Montreal"], answer: "Ottawa", points: 10 },
  { category: "🔬 Science", question: "Which organ pumps blood around the human body?", choices: ["Lung", "Kidney", "Heart", "Liver"], answer: "Heart", points: 10 },
  { category: "📚 History", question: "Which ancient civilization built roads across the Andes?", choices: ["Inca", "Maya", "Aztec", "Olmec"], answer: "Inca", points: 10 },
  { category: "🎨 Art & Culture", question: "Which art style uses tiny dots of color to form an image?", choices: ["Surrealism", "Minimalism", "Pointillism", "Cubism"], answer: "Pointillism", points: 10 },
  { category: "📚 History", question: "In which country did the Olympic Games begin?", choices: ["Italy", "Egypt", "Turkey", "Greece"], answer: "Greece", points: 10 },
  { category: "🌍 Geography", question: "Which river runs through Paris?", choices: ["River Seine", "River Thames", "River Tiber", "River Elbe"], answer: "River Seine", points: 10 },
  { category: "📚 History", question: "Which ancient civilization built the pyramids at Giza?", choices: ["Ancient Egyptians", "Ancient Greeks", "Romans", "Vikings"], answer: "Ancient Egyptians", points: 10 },
  { category: "📖 Language", question: "What is the past tense of 'go'?", choices: ["Gone", "Going", "Went", "Goed"], answer: "Went", points: 10 },
  { category: "🔬 Science", question: "What type of animal is a frog?", choices: ["Bird", "Amphibian", "Reptile", "Mammal"], answer: "Amphibian", points: 10 },
  { category: "🔢 Math", question: "Which number is a multiple of both 3 and 4?", choices: ["18", "12", "9", "16"], answer: "12", points: 10 },
  { category: "🎨 Art & Culture", question: "Who painted The Arnolfini Portrait?", choices: ["Pieter Bruegel", "Jan van Eyck", "Albrecht Dürer", "Hans Holbein"], answer: "Jan van Eyck", points: 10 },
  { category: "🎨 Art & Culture", question: "What is the art of beautiful handwriting called?", choices: ["Choreography", "Photography", "Calligraphy", "Lithography"], answer: "Calligraphy", points: 10 },
  { category: "🍎 Nature", question: "Which is the largest living animal?", choices: ["Giant squid", "Blue whale", "African elephant", "Whale shark"], answer: "Blue whale", points: 10 },
  { category: "📚 History", question: "Which city was buried by Mount Vesuvius in AD 79?", choices: ["Sparta", "Carthage", "Pompeii", "Athens"], answer: "Pompeii", points: 10 },
  { category: "🎨 Art & Culture", question: "Which performing art tells a story mainly through movement and music?", choices: ["Sculpture", "Photography", "Architecture", "Ballet"], answer: "Ballet", points: 10 },
  { category: "🍎 Nature", question: "What is the change from caterpillar to butterfly called?", choices: ["Pollination", "Hibernation", "Metamorphosis", "Migration"], answer: "Metamorphosis", points: 10 },
  { category: "🔬 Science", question: "Which vessel carries oxygenated blood from the lungs to the heart?", choices: ["Pulmonary artery", "Aorta", "Vena cava", "Pulmonary vein"], answer: "Pulmonary vein", points: 10 },
  { category: "📚 History", question: "Which explorer reached the Americas in 1492?", choices: ["Zheng He", "Christopher Columbus", "James Cook", "Marco Polo"], answer: "Christopher Columbus", points: 10 },
  { category: "🔢 Math", question: "What is one quarter of 100?", choices: ["50", "25", "20", "40"], answer: "25", points: 10 },
  { category: "📚 History", question: "Which agreement ended the Thirty Years' War in 1648?", choices: ["Treaty of Paris", "Congress of Vienna", "Peace of Westphalia", "Treaty of Utrecht"], answer: "Peace of Westphalia", points: 10 },
  { category: "🌍 Geography", question: "Which country shares the Iberian Peninsula with Spain?", choices: ["Morocco", "Portugal", "France", "Italy"], answer: "Portugal", points: 10 },
  { category: "🔬 Science", question: "Which gas do plants absorb during photosynthesis?", choices: ["Nitrogen", "Carbon dioxide", "Oxygen", "Helium"], answer: "Carbon dioxide", points: 10 },
  { category: "📚 History", question: "Who crossed the Alps with elephants during the Second Punic War?", choices: ["Hasdrubal", "Hamilcar", "Hannibal", "Scipio"], answer: "Hannibal", points: 10 },
  { category: "🍎 Nature", question: "What process releases water vapor from plant leaves?", choices: ["Guttation", "Fermentation", "Transpiration", "Respiration"], answer: "Transpiration", points: 10 },
  { category: "📚 History", question: "Which queen ruled Britain for much of the 19th century?", choices: ["Queen Mary I", "Queen Victoria", "Queen Anne", "Queen Elizabeth I"], answer: "Queen Victoria", points: 10 },
  { category: "📖 Language", question: "Which punctuation mark ends a direct question?", choices: ["Question mark", "Comma", "Colon", "Apostrophe"], answer: "Question mark", points: 10 },
  { category: "🍎 Nature", question: "What is an animal that generates most body heat internally called?", choices: ["Ectotherm", "Detritivore", "Autotroph", "Endotherm"], answer: "Endotherm", points: 10 },
  { category: "🔬 Science", question: "Which material is attracted strongly to a magnet?", choices: ["Rubber", "Iron", "Glass", "Wood"], answer: "Iron", points: 10 },
  { category: "🔢 Math", question: "Which fraction is equal to one half?", choices: ["6/8", "4/8", "3/8", "5/8"], answer: "4/8", points: 10 },
  { category: "📚 History", question: "Who was the first person in space?", choices: ["Neil Armstrong", "John Glenn", "Buzz Aldrin", "Yuri Gagarin"], answer: "Yuri Gagarin", points: 10 },
  { category: "📚 History", question: "Who is credited with inventing the telephone?", choices: ["Thomas Edison", "Nikola Tesla", "James Watt", "Alexander Graham Bell"], answer: "Alexander Graham Bell", points: 10 },
  { category: "📖 Language", question: "What is the plural of 'child'?", choices: ["Children", "Childs", "Childes", "Childrens"], answer: "Children", points: 10 },
  { category: "📖 Language", question: "Which figure of speech uses a part to represent the whole?", choices: ["Oxymoron", "Hyperbole", "Anaphora", "Synecdoche"], answer: "Synecdoche", points: 10 },
  { category: "📚 History", question: "Which ancient city was famous for its Hanging Gardens?", choices: ["Babylon", "Sparta", "Memphis", "Carthage"], answer: "Babylon", points: 10 },
  { category: "🎨 Art & Culture", question: "What is a self-portrait?", choices: ["A group sculpture", "An abstract pattern", "An artist's image of themself", "A landscape painting"], answer: "An artist's image of themself", points: 10 },
  { category: "🍎 Nature", question: "Which soil layer usually contains the most humus?", choices: ["Topsoil", "Subsoil", "Parent material", "Bedrock"], answer: "Topsoil", points: 10 },
  { category: "🍎 Nature", question: "Which tree is known for producing maple syrup?", choices: ["Cedar", "Maple", "Birch", "Elm"], answer: "Maple", points: 10 },
  { category: "🔬 Science", question: "What gas do humans need to breathe?", choices: ["Neon", "Oxygen", "Carbon dioxide", "Hydrogen"], answer: "Oxygen", points: 10 },
  { category: "🔢 Math", question: "How many sides does a hexagon have?", choices: ["6", "5", "7", "8"], answer: "6", points: 10 },

  // ── 🔥 DIFFICULT ROUND (Questions 40–50) ─────────────────
  { category: "🔬 Science", question: "Which element has the chemical symbol Fe?", choices: ["Fluorine", "Iron", "Francium", "Fermium"], answer: "Iron", points: 20 },
  { category: "📖 Language", question: "What is the term for a word that has the opposite meaning of another word?", choices: ["Synonym", "Homonym", "Antonym", "Acronym"], answer: "Antonym", points: 20 },
  { category: "🔬 Science", question: "Which layer of Earth's atmosphere contains most of the ozone layer?", choices: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], answer: "Stratosphere", points: 20 },
  { category: "📚 History", question: "Which civilization developed the writing system known as cuneiform?", choices: ["Sumerians", "Romans", "Vikings", "Aztecs"], answer: "Sumerians", points: 20 },
  { category: "🔢 Math", question: "What is the smallest prime number?", choices: ["0", "1", "2", "3"], answer: "2", points: 20 },
  { category: "🔬 Science", question: "Which scientist formulated the three laws of planetary motion?", choices: ["Johannes Kepler", "Galileo Galilei", "Isaac Newton", "Nicolaus Copernicus"], answer: "Johannes Kepler", points: 20 },
  { category: "🔬 Science", question: "Which blood vessels generally carry blood away from the heart?", choices: ["Veins", "Arteries", "Capillaries", "Venules"], answer: "Arteries", points: 20 },
  { category: "📖 Language", question: "Which of these languages belongs to the Romance language family?", choices: ["German", "Portuguese", "Arabic", "Japanese"], answer: "Portuguese", points: 20 },
  { category: "🔬 Science", question: "What is the SI unit of electric resistance?", choices: ["Volt", "Watt", "Ampere", "Ohm"], answer: "Ohm", points: 20 },
  { category: "📚 History", question: "Which ancient city was buried by the eruption of Mount Vesuvius in 79 CE?", choices: ["Pompeii", "Athens", "Carthage", "Alexandria"], answer: "Pompeii", points: 20 },
  { category: "🔬 Science", question: "Which part of the brain is primarily associated with balance and coordination?", choices: ["Cerebellum", "Hypothalamus", "Medulla oblongata", "Amygdala"], answer: "Cerebellum", points: 20 },

  // ── GAME 2 (Questions 51–89) ──────────────────────────────
  { category: "🎨 Art & Culture", question: "Who composed The Magic Flute?", choices: ["Claude Debussy", "Gustav Mahler", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven"], answer: "Wolfgang Amadeus Mozart", points: 10 },
  { category: "🎨 Art & Culture", question: "Which color do blue and yellow paint make when mixed?", choices: ["Green", "Purple", "Orange", "Brown"], answer: "Green", points: 10 },
  { category: "🌍 Geography", question: "Which country is shaped like a boot?", choices: ["Croatia", "Portugal", "Italy", "Greece"], answer: "Italy", points: 10 },
  { category: "🎨 Art & Culture", question: "Which museum displays the Mona Lisa?", choices: ["The Prado", "The Uffizi", "The Met", "The Louvre"], answer: "The Louvre", points: 10 },
  { category: "🎨 Art & Culture", question: "Who wrote Romeo and Juliet?", choices: ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"], answer: "William Shakespeare", points: 10 },
  { category: "🎨 Art & Culture", question: "Which author wrote The Jungle Book?", choices: ["H. G. Wells", "Rudyard Kipling", "Mark Twain", "Charles Dickens"], answer: "Rudyard Kipling", points: 10 },
  { category: "📖 Language", question: "Which word is spelled correctly?", choices: ["Neccessary", "Necessery", "Necessary", "Necesary"], answer: "Necessary", points: 10 },
  { category: "🍎 Nature", question: "What is a group of lions called?", choices: ["Pride", "Pack", "Herd", "Colony"], answer: "Pride", points: 10 },
  { category: "📖 Language", question: "What is the comparative form of 'good'?", choices: ["Gooder", "Best", "More good", "Better"], answer: "Better", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of Argentina?", choices: ["Santiago", "Montevideo", "Buenos Aires", "Lima"], answer: "Buenos Aires", points: 10 },
  { category: "📖 Language", question: "What term describes words that imitate sounds?", choices: ["Euphemism", "Alliteration", "Onomatopoeia", "Synecdoche"], answer: "Onomatopoeia", points: 10 },
  { category: "🎨 Art & Culture", question: "Which instrument has black and white keys?", choices: ["Drum", "Piano", "Violin", "Trumpet"], answer: "Piano", points: 10 },
  { category: "🌍 Geography", question: "Which country contains the city of Dubai?", choices: ["Saudi Arabia", "Oman", "United Arab Emirates", "Qatar"], answer: "United Arab Emirates", points: 10 },
  { category: "🌍 Geography", question: "Which country is home to Barcelona?", choices: ["Portugal", "Italy", "France", "Spain"], answer: "Spain", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of Kenya?", choices: ["Mombasa", "Kampala", "Addis Ababa", "Nairobi"], answer: "Nairobi", points: 10 },
  { category: "🔢 Math", question: "What is half of 84?", choices: ["38", "48", "42", "44"], answer: "42", points: 10 },
  { category: "🔬 Science", question: "Which blood cells help fight infection?", choices: ["Plasma cells", "White blood cells", "Red blood cells", "Platelets"], answer: "White blood cells", points: 10 },
  { category: "🍎 Nature", question: "Which animal has a shell and moves slowly on land?", choices: ["Cheetah", "Otter", "Falcon", "Tortoise"], answer: "Tortoise", points: 10 },
  { category: "🔢 Math", question: "What comes next: 5, 10, 15, 20?", choices: ["25", "22", "24", "30"], answer: "25", points: 10 },
  { category: "🔬 Science", question: "What is the freezing point of water in Celsius?", choices: ["10°C", "32°C", "100°C", "0°C"], answer: "0°C", points: 10 },
  { category: "🍎 Nature", question: "Which animal sleeps through much of winter?", choices: ["Zebra", "Giraffe", "Dolphin", "Bear"], answer: "Bear", points: 10 },
  { category: "🌍 Geography", question: "What is the largest island in the Mediterranean Sea?", choices: ["Sicily", "Sardinia", "Cyprus", "Crete"], answer: "Sicily", points: 10 },
  { category: "🍎 Nature", question: "What is a baby goat called?", choices: ["Chick", "Kid", "Calf", "Cub"], answer: "Kid", points: 10 },
  { category: "📚 History", question: "Which people sailed longships from Scandinavia?", choices: ["Vikings", "Samurai", "Spartans", "Aztecs"], answer: "Vikings", points: 10 },
  { category: "📚 History", question: "Which ancient people created democracy in Athens?", choices: ["Vikings", "Phoenicians", "Greeks", "Romans"], answer: "Greeks", points: 10 },
  { category: "🔢 Math", question: "How many degrees are in a right angle?", choices: ["45°", "180°", "360°", "90°"], answer: "90°", points: 10 },
  { category: "🔬 Science", question: "What is the most abundant element in Earth's crust by mass?", choices: ["Oxygen", "Silicon", "Aluminum", "Iron"], answer: "Oxygen", points: 10 },
  { category: "📚 History", question: "Which war ended in 1945?", choices: ["Crimean War", "American Civil War", "World War II", "World War I"], answer: "World War II", points: 10 },
  { category: "🌍 Geography", question: "Which river forms part of the Germany–Poland border?", choices: ["Main", "Oder", "Elbe", "Weser"], answer: "Oder", points: 10 },
  { category: "🔬 Science", question: "Which part of the digestive system absorbs most nutrients?", choices: ["Large intestine", "Esophagus", "Small intestine", "Stomach"], answer: "Small intestine", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of Egypt?", choices: ["Giza", "Luxor", "Cairo", "Alexandria"], answer: "Cairo", points: 10 },
  { category: "🔬 Science", question: "What kind of energy is stored in food?", choices: ["Sound energy", "Light energy", "Nuclear energy", "Chemical energy"], answer: "Chemical energy", points: 10 },
  { category: "🌍 Geography", question: "Which continent is Argentina part of?", choices: ["South America", "North America", "Europe", "Africa"], answer: "South America", points: 10 },
  { category: "🎨 Art & Culture", question: "What is the Japanese theatrical form known for elaborate makeup?", choices: ["Kabuki", "Bharatanatyam", "Flamenco", "Opera buffa"], answer: "Kabuki", points: 10 },
  { category: "🎨 Art & Culture", question: "What is a person who writes music called?", choices: ["Composer", "Sculptor", "Curator", "Director"], answer: "Composer", points: 10 },
  { category: "🎨 Art & Culture", question: "Which novel features a whale named Moby Dick?", choices: ["The Old Man and the Sea", "Moby-Dick", "Treasure Island", "Robinson Crusoe"], answer: "Moby-Dick", points: 10 },
  { category: "🔬 Science", question: "Which organ pumps blood around the human body?", choices: ["Lung", "Kidney", "Heart", "Liver"], answer: "Heart", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of Thailand?", choices: ["Phnom Penh", "Bangkok", "Hanoi", "Manila"], answer: "Bangkok", points: 10 },

  // ── GAME 3 (Questions 101–200) ──────────────────────────────
  { category: "🔬 Science", question: "Which human sense organ detects sound?", choices: ["Eye", "Nose", "Tongue", "Ear"], answer: "Ear", points: 10 },
  { category: "🔬 Science", question: "What instrument is used to view very small objects?", choices: ["Periscope", "Stethoscope", "Microscope", "Telescope"], answer: "Microscope", points: 10 },
  { category: "📖 Language", question: "Which sentence uses a semicolon correctly?", choices: ["The; storm ended, we continued.", "The storm ended; we continued our journey.", "The storm; ended we continued.", "The storm ended we; continued."], answer: "The storm ended; we continued our journey.", points: 10 },
  { category: "🎨 Art & Culture", question: "What is a haiku traditionally associated with?", choices: ["Italian opera", "French painting", "Indian dance", "Japanese poetry"], answer: "Japanese poetry", points: 10 },
  { category: "🔬 Science", question: "Which law links pressure and volume inversely at constant temperature?", choices: ["Hooke's law", "Boyle's law", "Charles's law", "Ohm's law"], answer: "Boyle's law", points: 10 },
  { category: "🌍 Geography", question: "Which country has the exclave of Cabinda?", choices: ["Angola", "Gabon", "Cameroon", "Namibia"], answer: "Angola", points: 10 },
  { category: "🌍 Geography", question: "Which country is Kyoto in?", choices: ["Japan", "China", "South Korea", "Thailand"], answer: "Japan", points: 10 },
  { category: "📚 History", question: "The Renaissance began in which country?", choices: ["Italy", "France", "England", "Spain"], answer: "Italy", points: 10 },
  { category: "📚 History", question: "Which ancient civilization used hieroglyphics?", choices: ["Mongols", "Ancient Egyptians", "Ancient Romans", "Vikings"], answer: "Ancient Egyptians", points: 10 },
  { category: "📚 History", question: "Which empire controlled the western end of the Silk Road for centuries?", choices: ["Inca Empire", "Roman Empire", "Aztec Empire", "Mali Empire"], answer: "Roman Empire", points: 10 },
  { category: "🔬 Science", question: "Which part of a plant absorbs water from the soil?", choices: ["Leaves", "Fruit", "Roots", "Flowers"], answer: "Roots", points: 10 },
  { category: "📖 Language", question: "What is a word formed from initials and pronounced as a word?", choices: ["Acronym", "Homonym", "Portmanteau", "Epithet"], answer: "Acronym", points: 10 },
  { category: "📖 Language", question: "What is the smallest sound unit that can distinguish meaning?", choices: ["Grapheme", "Lexeme", "Phoneme", "Morpheme"], answer: "Phoneme", points: 10 },
  { category: "🎨 Art & Culture", question: "Who wrote One Hundred Years of Solitude?", choices: ["Pablo Neruda", "Mario Vargas Llosa", "Gabriel García Márquez", "Jorge Luis Borges"], answer: "Gabriel García Márquez", points: 10 },
  { category: "📚 History", question: "Which invention is Johannes Gutenberg famous for improving?", choices: ["Printing press", "Steam engine", "Telephone", "Telescope"], answer: "Printing press", points: 10 },
  { category: "🔢 Math", question: "What is 25% of 80?", choices: ["20", "15", "25", "30"], answer: "20", points: 10 },
  { category: "📖 Language", question: "Which word is a synonym for 'happy'?", choices: ["Angry", "Tired", "Quiet", "Joyful"], answer: "Joyful", points: 10 },
  { category: "🔢 Math", question: "How many centimeters are in one meter?", choices: ["1,000", "60", "100", "10"], answer: "100", points: 10 },
  { category: "🔬 Science", question: "What is Earth's natural satellite?", choices: ["Mars", "Venus", "Moon", "Sun"], answer: "Moon", points: 10 },
  { category: "🍎 Nature", question: "What do carnivores mainly eat?", choices: ["Nectar", "Seeds", "Meat", "Plants"], answer: "Meat", points: 10 },
  { category: "🔬 Science", question: "What is the SI unit of electric capacitance?", choices: ["Weber", "Siemens", "Farad", "Tesla"], answer: "Farad", points: 10 },
  { category: "🌍 Geography", question: "Which country contains the city of Salzburg?", choices: ["Belgium", "Austria", "Switzerland", "Germany"], answer: "Austria", points: 10 },
  { category: "🎨 Art & Culture", question: "Who sculpted David during the Renaissance?", choices: ["Bernini", "Rodin", "Michelangelo", "Donatello"], answer: "Michelangelo", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of Norway?", choices: ["Copenhagen", "Helsinki", "Oslo", "Stockholm"], answer: "Oslo", points: 10 },
  { category: "🔢 Math", question: "What is the chance of rolling a sum of 7 with two fair dice?", choices: ["1/6", "1/12", "1/8", "1/4"], answer: "1/6", points: 10 },
  { category: "🔬 Science", question: "Which planet is farthest from the Sun?", choices: ["Neptune", "Uranus", "Saturn", "Jupiter"], answer: "Neptune", points: 10 },
  { category: "🔢 Math", question: "What is 8 multiplied by 6?", choices: ["42", "54", "56", "48"], answer: "48", points: 10 },
  { category: "🔢 Math", question: "What is 15 + 27?", choices: ["42", "32", "41", "52"], answer: "42", points: 10 },
  { category: "🔬 Science", question: "What force pulls objects toward Earth?", choices: ["Friction", "Magnetism", "Buoyancy", "Gravity"], answer: "Gravity", points: 10 },
  { category: "🎨 Art & Culture", question: "Which dance originated in Argentina and Uruguay?", choices: ["Kabuki", "Tango", "Ballet", "Hula"], answer: "Tango", points: 10 },
  { category: "📚 History", question: "Who wrote the Declaration of Independence's first draft?", choices: ["George Washington", "Benjamin Franklin", "James Madison", "Thomas Jefferson"], answer: "Thomas Jefferson", points: 10 },
  { category: "🔢 Math", question: "What is 96 divided by 8?", choices: ["14", "16", "12", "10"], answer: "12", points: 10 },
  { category: "🔬 Science", question: "Which planet is closest in size to Earth?", choices: ["Neptune", "Venus", "Mars", "Mercury"], answer: "Venus", points: 10 },
  { category: "🔬 Science", question: "Which simple machine is a ramp?", choices: ["Pulley", "Lever", "Wheel and axle", "Inclined plane"], answer: "Inclined plane", points: 10 },
  { category: "🍎 Nature", question: "Which animal shares the family Giraffidae with the giraffe?", choices: ["Eland", "Okapi", "Kudu", "Impala"], answer: "Okapi", points: 10 },
  { category: "🌍 Geography", question: "Which body of water separates Saudi Arabia from Africa?", choices: ["Red Sea", "Black Sea", "Caspian Sea", "Baltic Sea"], answer: "Red Sea", points: 10 },
  { category: "📚 History", question: "Who was a famous female pharaoh of ancient Egypt?", choices: ["Artemisia", "Hatshepsut", "Boudica", "Zenobia"], answer: "Hatshepsut", points: 10 },
  { category: "🔢 Math", question: "What is 9 multiplied by 7?", choices: ["56", "72", "67", "63"], answer: "63", points: 10 },
  { category: "📚 History", question: "Who founded the Maurya Empire?", choices: ["Samudragupta", "Chandragupta Maurya", "Ashoka", "Harsha"], answer: "Chandragupta Maurya", points: 10 },
  { category: "📚 History", question: "Who was the first president of the United States?", choices: ["Thomas Jefferson", "Abraham Lincoln", "John Adams", "George Washington"], answer: "George Washington", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of Canada?", choices: ["Ottawa", "Toronto", "Vancouver", "Montreal"], answer: "Ottawa", points: 10 },
  { category: "🎨 Art & Culture", question: "Who wrote The Little Prince?", choices: ["Jules Verne", "Albert Camus", "Antoine de Saint-Exupéry", "Victor Hugo"], answer: "Antoine de Saint-Exupéry", points: 10 },
  { category: "🌍 Geography", question: "Which ocean lies east of the United States?", choices: ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"], answer: "Atlantic Ocean", points: 10 },
  { category: "🔬 Science", question: "What is the center of an atom called?", choices: ["Nucleus", "Membrane", "Orbit", "Core cell"], answer: "Nucleus", points: 10 },
  { category: "🎨 Art & Culture", question: "Which composer wrote The Four Seasons?", choices: ["Wolfgang Mozart", "Johann Bach", "Frédéric Chopin", "Antonio Vivaldi"], answer: "Antonio Vivaldi", points: 10 },
  { category: "🔢 Math", question: "What is the perimeter of a square with 6 cm sides?", choices: ["24 cm", "12 cm", "30 cm", "36 cm"], answer: "24 cm", points: 10 },
  { category: "🎨 Art & Culture", question: "Which composer wrote The Marriage of Figaro?", choices: ["Wolfgang Amadeus Mozart", "Giuseppe Verdi", "Giacomo Puccini", "Richard Wagner"], answer: "Wolfgang Amadeus Mozart", points: 10 },
  { category: "🌍 Geography", question: "Which continent contains the country of Mongolia?", choices: ["Europe", "Africa", "South America", "Asia"], answer: "Asia", points: 10 },
  { category: "🍎 Nature", question: "Which biome has dry summers and shrub-dominated vegetation?", choices: ["Taiga", "Tundra", "Savanna", "Chaparral"], answer: "Chaparral", points: 10 },
  { category: "🎨 Art & Culture", question: "Who painted The Starry Night?", choices: ["Vincent van Gogh", "Claude Monet", "Pablo Picasso", "Rembrandt"], answer: "Vincent van Gogh", points: 10 },
  { category: "🌍 Geography", question: "Which river flows through London?", choices: ["River Seine", "River Rhine", "River Danube", "River Thames"], answer: "River Thames", points: 10 },
  { category: "🔢 Math", question: "What is the perimeter of a triangle with sides 3 cm, 4 cm, and 5 cm?", choices: ["10 cm", "15 cm", "20 cm", "12 cm"], answer: "12 cm", points: 10 },
  { category: "🔬 Science", question: "Which star is closest to Earth?", choices: ["The Sun", "Sirius", "Polaris", "Betelgeuse"], answer: "The Sun", points: 10 },
  { category: "🎨 Art & Culture", question: "Which family of instruments includes the cello?", choices: ["Percussion family", "String family", "Brass family", "Woodwind family"], answer: "String family", points: 10 },
  { category: "🔬 Science", question: "Which device converts electrical energy into light?", choices: ["Battery", "Generator", "Thermometer", "Light bulb"], answer: "Light bulb", points: 10 },
  { category: "📚 History", question: "Which country gave the Statue of Liberty to the United States?", choices: ["Spain", "Italy", "Germany", "France"], answer: "France", points: 10 },
  { category: "🌍 Geography", question: "Which sea lies between Europe and Africa?", choices: ["Caribbean Sea", "Baltic Sea", "Arabian Sea", "Mediterranean Sea"], answer: "Mediterranean Sea", points: 10 },
  { category: "🔬 Science", question: "Which sense is mainly associated with the tongue?", choices: ["Hearing", "Touch", "Taste", "Sight"], answer: "Taste", points: 10 },
  { category: "📚 History", question: "Which empire used gladiators in arena contests?", choices: ["Roman Empire", "Mughal Empire", "Mali Empire", "Ottoman Empire"], answer: "Roman Empire", points: 10 },
  { category: "📚 History", question: "Which city was divided by a wall from 1961 to 1989?", choices: ["Vienna", "Warsaw", "Prague", "Berlin"], answer: "Berlin", points: 10 },
  { category: "🔬 Science", question: "How many planets are in our Solar System?", choices: ["Eight", "Seven", "Nine", "Ten"], answer: "Eight", points: 10 },
  { category: "🌍 Geography", question: "Which US state is made up entirely of islands?", choices: ["Hawaii", "Alaska", "Florida", "California"], answer: "Hawaii", points: 10 },
  { category: "🌍 Geography", question: "Which continent is crossed by both the Equator and the Prime Meridian?", choices: ["Europe", "Africa", "Asia", "South America"], answer: "Africa", points: 10 },
  { category: "📖 Language", question: "What type of word is 'slowly'?", choices: ["Conjunction", "Adverb", "Noun", "Pronoun"], answer: "Adverb", points: 10 },
  { category: "📖 Language", question: "Which sentence is in the future tense?", choices: ["They will travel tomorrow.", "They traveled yesterday.", "They travel often.", "They are traveling now."], answer: "They will travel tomorrow.", points: 10 },
  { category: "🔬 Science", question: "What happens to water at 100°C at standard pressure?", choices: ["It condenses", "It crystallizes", "It boils", "It freezes"], answer: "It boils", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of South Korea?", choices: ["Beijing", "Seoul", "Busan", "Tokyo"], answer: "Seoul", points: 10 },
  { category: "🎨 Art & Culture", question: "What material is traditionally folded in origami?", choices: ["Paper", "Clay", "Wood", "Glass"], answer: "Paper", points: 10 },
  { category: "🌍 Geography", question: "Which mountain is the highest in Africa?", choices: ["Mount Kenya", "Mount Elgon", "Mount Stanley", "Mount Kilimanjaro"], answer: "Mount Kilimanjaro", points: 10 },
  { category: "📚 History", question: "Who delivered the 'I Have a Dream' speech?", choices: ["Malcolm X", "Barack Obama", "Martin Luther King Jr.", "Nelson Mandela"], answer: "Martin Luther King Jr.", points: 10 },
  { category: "📚 History", question: "Which civilization built the Colosseum?", choices: ["Romans", "Greeks", "Egyptians", "Persians"], answer: "Romans", points: 10 },
  { category: "🎨 Art & Culture", question: "Which artist painted a famous series of water lilies?", choices: ["Andy Warhol", "Claude Monet", "Salvador Dalí", "Edvard Munch"], answer: "Claude Monet", points: 10 },
  { category: "🌍 Geography", question: "Which continent contains the Sahara Desert?", choices: ["Australia", "South America", "Africa", "Asia"], answer: "Africa", points: 10 },
  { category: "🔢 Math", question: "Which number is even?", choices: ["33", "45", "28", "17"], answer: "28", points: 10 },
  { category: "🌍 Geography", question: "Which European country is famous for its tulip fields and windmills?", choices: ["Austria", "Ireland", "Netherlands", "Poland"], answer: "Netherlands", points: 10 },
  { category: "📚 History", question: "Which civilization flourished in the city of Teotihuacan?", choices: ["Vikings", "A pre-Aztec Mesoamerican civilization", "Romans", "Incas"], answer: "A pre-Aztec Mesoamerican civilization", points: 10 },
  { category: "🔢 Math", question: "What is the next number in the pattern 2, 4, 8, 16?", choices: ["24", "30", "34", "32"], answer: "32", points: 10 },
  { category: "🎨 Art & Culture", question: "Which Japanese aesthetic values imperfection and impermanence?", choices: ["Ukiyo-e", "Ikebana", "Kabuki", "Wabi-sabi"], answer: "Wabi-sabi", points: 10 },
  { category: "🎨 Art & Culture", question: "What do actors perform on in a theater?", choices: ["Studio", "Orchestra pit", "Stage", "Gallery"], answer: "Stage", points: 10 },
  { category: "🌍 Geography", question: "Which mountain range separates much of Europe from Asia?", choices: ["Rocky Mountains", "Ural Mountains", "Alps", "Andes"], answer: "Ural Mountains", points: 10 },
  { category: "🎨 Art & Culture", question: "Which instrument belongs to the brass family?", choices: ["Trombone", "Violin", "Oboe", "Harp"], answer: "Trombone", points: 10 },
  { category: "🔬 Science", question: "Which part of a flower usually develops into a fruit?", choices: ["Stamen", "Ovary", "Petal", "Sepal"], answer: "Ovary", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of Kyrgyzstan?", choices: ["Dushanbe", "Tashkent", "Astana", "Bishkek"], answer: "Bishkek", points: 10 },
  { category: "🔢 Math", question: "What is the area of a 7 cm by 4 cm rectangle?", choices: ["35 cm²", "28 cm²", "22 cm²", "14 cm²"], answer: "28 cm²", points: 10 },
  { category: "📖 Language", question: "What is the opposite of 'ancient'?", choices: ["Old", "Historic", "Broken", "Modern"], answer: "Modern", points: 10 },
  { category: "🎨 Art & Culture", question: "Which instrument usually has six strings?", choices: ["Flute", "Trumpet", "Clarinet", "Guitar"], answer: "Guitar", points: 10 },
  { category: "🔢 Math", question: "What is 144 divided by 12?", choices: ["14", "16", "12", "10"], answer: "12", points: 10 },
  { category: "🔢 Math", question: "If log10(x) = 3, what is x?", choices: ["100", "1000", "30", "300"], answer: "1000", points: 10 },
  { category: "🎨 Art & Culture", question: "Which instrument is played with a bow?", choices: ["Saxophone", "Piano", "Tambourine", "Violin"], answer: "Violin", points: 10 },
  { category: "🔢 Math", question: "What is 18 + 24?", choices: ["42", "40", "44", "46"], answer: "42", points: 10 },
  { category: "🍎 Nature", question: "Which bird is known for copying human speech?", choices: ["Parrot", "Penguin", "Ostrich", "Swan"], answer: "Parrot", points: 10 },
  { category: "📚 History", question: "Which ship sank on its first voyage in 1912?", choices: ["Endeavour", "Titanic", "Mayflower", "Santa Maria"], answer: "Titanic", points: 10 },
  { category: "🔬 Science", question: "What is the chemical symbol for oxygen?", choices: ["O", "Ox", "Og", "Om"], answer: "O", points: 10 },
  { category: "📚 History", question: "Which document limited the English king's power in 1215?", choices: ["Bill of Rights", "Treaty of Paris", "Magna Carta", "Domesday Book"], answer: "Magna Carta", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of Vietnam?", choices: ["Ho Chi Minh City", "Hue", "Da Nang", "Hanoi"], answer: "Hanoi", points: 10 },
  { category: "🌍 Geography", question: "Which country has a maple leaf on its flag?", choices: ["Austria", "Denmark", "Finland", "Canada"], answer: "Canada", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of Portugal?", choices: ["Lisbon", "Madrid", "Porto", "Seville"], answer: "Lisbon", points: 10 },
  { category: "🔬 Science", question: "What is H2O commonly called?", choices: ["Salt", "Oxygen", "Hydrogen", "Water"], answer: "Water", points: 10 },
  { category: "🌍 Geography", question: "Which strait separates Sicily from mainland Italy?", choices: ["Bosporus", "Dardanelles", "Strait of Messina", "Strait of Gibraltar"], answer: "Strait of Messina", points: 10 },
  { category: "🔬 Science", question: "Which part of an atom has a positive charge?", choices: ["Proton", "Electron", "Neutron", "Photon"], answer: "Proton", points: 10 },

  // ── GAME 4 (Questions 201–250) ──────────────────────────────
  { category: "📚 History", question: "Who was the first person to walk on the Moon?", choices: ["Yuri Gagarin", "Buzz Aldrin", "John Glenn", "Neil Armstrong"], answer: "Neil Armstrong", points: 10 },
  { category: "🌍 Geography", question: "What is the capital of New Zealand?", choices: ["Hamilton", "Wellington", "Auckland", "Christchurch"], answer: "Wellington", points: 10 },
  { category: "🎨 Art & Culture", question: "Who wrote Alice's Adventures in Wonderland?", choices: ["C. S. Lewis", "Lewis Carroll", "Roald Dahl", "J. M. Barrie"], answer: "Lewis Carroll", points: 10 },
  { category: "🔢 Math", question: "What is the sum of the interior angles of a decagon?", choices: ["1260°", "1620°", "1800°", "1440°"], answer: "1440°", points: 10 },
  { category: "🎨 Art & Culture", question: "Which country is flamenco most closely associated with?", choices: ["Greece", "Brazil", "Ireland", "Spain"], answer: "Spain", points: 10 },
  { category: "📚 History", question: "Which Chinese dynasty built most of the existing Great Wall?", choices: ["Ming dynasty", "Han dynasty", "Tang dynasty", "Song dynasty"], answer: "Ming dynasty", points: 10 },
  { category: "📖 Language", question: "Which word is an adjective in 'The red ball bounced'?", choices: ["The", "Red", "Ball", "Bounced"], answer: "Red", points: 10 },
  { category: "📚 History", question: "What was the capital of the Inca Empire?", choices: ["Quito", "Lima", "Tiwanaku", "Cusco"], answer: "Cusco", points: 10 },
  { category: "🔬 Science", question: "Which organelle modifies and packages proteins?", choices: ["Ribosome", "Lysosome", "Centriole", "Golgi apparatus"], answer: "Golgi apparatus", points: 10 },
  { category: "🎨 Art & Culture", question: "Which architectural order uses acanthus-leaf capitals?", choices: ["Tuscan", "Corinthian", "Doric", "Ionic"], answer: "Corinthian", points: 10 },
  { category: "🎨 Art & Culture", question: "Who wrote Pride and Prejudice?", choices: ["Mary Shelley", "Jane Austen", "Emily Brontë", "Virginia Woolf"], answer: "Jane Austen", points: 10 },
  { category: "🔢 Math", question: "What is the least common multiple of 18 and 24?", choices: ["48", "144", "72", "36"], answer: "72", points: 10 },
  { category: "📚 History", question: "Which nurse became known as the Lady with the Lamp?", choices: ["Mary Seacole", "Edith Cavell", "Florence Nightingale", "Clara Barton"], answer: "Florence Nightingale", points: 10 },
  { category: "🔬 Science", question: "What is the change from a solid to a liquid called?", choices: ["Evaporation", "Melting", "Freezing", "Condensation"], answer: "Melting", points: 10 },
  { category: "📚 History", question: "Who was known as the Maid of Orléans?", choices: ["Catherine the Great", "Florence Nightingale", "Joan of Arc", "Marie Curie"], answer: "Joan of Arc", points: 10 },
  { category: "🔢 Math", question: "What is 30% of 50?", choices: ["25", "15", "10", "20"], answer: "15", points: 10 },
  { category: "🔢 Math", question: "How many minutes are in two hours?", choices: ["60", "90", "180", "120"], answer: "120", points: 10 },
  { category: "🔬 Science", question: "Which state of matter has a fixed volume but no fixed shape?", choices: ["Gas", "Plasma", "Liquid", "Solid"], answer: "Liquid", points: 10 },
  { category: "🔢 Math", question: "What is the derivative of sin(x)?", choices: ["cos(x)", "−sin(x)", "tan(x)", "sec²(x)"], answer: "cos(x)", points: 10 },
  { category: "🍎 Nature", question: "Which animal is the largest living land animal?", choices: ["Hippopotamus", "Rhinoceros", "African elephant", "Giraffe"], answer: "African elephant", points: 10 },
  { category: "📖 Language", question: "What punctuation mark is used to show possession?", choices: ["Comma", "Semicolon", "Apostrophe", "Colon"], answer: "Apostrophe", points: 10 },
  { category: "🌍 Geography", question: "Which country is home to the ruins of Troy?", choices: ["Greece", "Italy", "Turkey", "Lebanon"], answer: "Turkey", points: 10 },
  { category: "🔬 Science", question: "What is the name of the longest bone in the human body?", choices: ["Tibia", "Humerus", "Femur", "Fibula"], answer: "Femur", points: 10 },
  { category: "📚 History", question: "Which civilisation invented the wheel?", choices: ["Ancient Egyptians", "Romans", "Sumerians", "Greeks"], answer: "Sumerians", points: 10 },
  { category: "🎨 Art & Culture", question: "Which painting technique involves applying thick paint to a canvas with a palette knife?", choices: ["Fresco", "Watercolour", "Impasto", "Tempera"], answer: "Impasto", points: 10 },
  { category: "🔢 Math", question: "What is the highest common factor (HCF) of 24 and 36?", choices: ["6", "8", "12", "18"], answer: "12", points: 10 },
  { category: "🍎 Nature", question: "Which planet is known as the 'Morning Star' or 'Evening Star'?", choices: ["Mars", "Venus", "Mercury", "Jupiter"], answer: "Venus", points: 10 },
  { category: "📖 Language", question: "What is the term for a word formed from the initial letters of other words, such as NASA?", choices: ["Abbreviation", "Acronym", "Initialism", "Contraction"], answer: "Acronym", points: 10 },
  { category: "🌍 Geography", question: "What is the name of the strait that connects the Atlantic and Pacific Oceans at the southern tip of South America?", choices: ["Drake Passage", "Strait of Magellan", "Strait of Gibraltar", "Torres Strait"], answer: "Strait of Magellan", points: 10 },
  { category: "🔬 Science", question: "Which type of electromagnetic radiation has the shortest wavelength?", choices: ["Radio waves", "Visible light", "X-rays", "Gamma rays"], answer: "Gamma rays", points: 10 },
  { category: "📚 History", question: "In which city did Rosa Parks refuse to give up her bus seat in 1955?", choices: ["Birmingham", "Atlanta", "Montgomery", "Memphis"], answer: "Montgomery", points: 10 },
  { category: "🎨 Art & Culture", question: "Which author created the detective Sherlock Holmes?", choices: ["Agatha Christie", "Arthur Conan Doyle", "Raymond Chandler", "G.K. Chesterton"], answer: "Arthur Conan Doyle", points: 10 },
  { category: "🔢 Math", question: "What is the name of a polygon with ten sides?", choices: ["Nonagon", "Decagon", "Octagon", "Heptagon"], answer: "Decagon", points: 10 },
  { category: "🍎 Nature", question: "What is the name of the deepest ocean trench on Earth?", choices: ["Puerto Rico Trench", "Java Trench", "Mariana Trench", "Tonga Trench"], answer: "Mariana Trench", points: 10 },
  { category: "📖 Language", question: "Which of these is an example of a simile?", choices: ["The world is a stage.", "He ran like the wind.", "The stars danced.", "Time flew by."], answer: "He ran like the wind.", points: 10 },
  { category: "🌍 Geography", question: "Which country is home to the ancient Inca ruins of Machu Picchu?", choices: ["Bolivia", "Chile", "Ecuador", "Peru"], answer: "Peru", points: 10 },
  { category: "🔬 Science", question: "What is the main gas found inside the Sun?", choices: ["Oxygen", "Helium", "Hydrogen", "Nitrogen"], answer: "Hydrogen", points: 10 },
  { category: "📚 History", question: "Which leader was known as 'El Libertador' for liberating much of South America from Spanish rule?", choices: ["José de San Martín", "Simón Bolívar", "Toussaint Louverture", "Miguel Hidalgo"], answer: "Simón Bolívar", points: 10 },
  { category: "🎨 Art & Culture", question: "What style of music originated in New Orleans in the early 20th century?", choices: ["Blues", "Jazz", "Rock", "Gospel"], answer: "Jazz", points: 10 },
  { category: "🔢 Math", question: "What is 20% of 350?", choices: ["60", "65", "70", "75"], answer: "70", points: 10 },
  { category: "🍎 Nature", question: "Which organ in the human body produces bile?", choices: ["Pancreas", "Spleen", "Liver", "Stomach"], answer: "Liver", points: 10 },
  { category: "📖 Language", question: "What is the term for a story in which characters and events represent abstract ideas or moral qualities?", choices: ["Fable", "Allegory", "Parable", "Myth"], answer: "Allegory", points: 10 },
  { category: "🌍 Geography", question: "Which African country has the most pyramids?", choices: ["Egypt", "Libya", "Ethiopia", "Sudan"], answer: "Sudan", points: 10 },
  { category: "🔬 Science", question: "What is the name of the process by which a solid turns directly into a gas?", choices: ["Evaporation", "Condensation", "Sublimation", "Melting"], answer: "Sublimation", points: 10 },
  { category: "📚 History", question: "Which country launched the world's first artificial satellite, Sputnik, in 1957?", choices: ["United States", "China", "Soviet Union", "Germany"], answer: "Soviet Union", points: 10 },
  { category: "🎨 Art & Culture", question: "Which famous music festival was held in Woodstock, New York in 1969?", choices: ["Coachella", "Glastonbury", "Woodstock Festival", "Lollapalooza"], answer: "Woodstock Festival", points: 10 },
  { category: "🔢 Math", question: "What is the sum of the first five positive integers?", choices: ["10", "12", "15", "20"], answer: "15", points: 10 },
  { category: "🍎 Nature", question: "What type of animal is a Komodo dragon?", choices: ["Snake", "Crocodile", "Lizard", "Turtle"], answer: "Lizard", points: 10 },
  { category: "📖 Language", question: "What is the name for words that are spelled the same forwards and backwards, such as 'racecar'?", choices: ["Anagram", "Palindrome", "Homonym", "Acronym"], answer: "Palindrome", points: 10 },
  { category: "🌍 Geography", question: "In which country would you find the city of Casablanca?", choices: ["Tunisia", "Algeria", "Morocco", "Libya"], answer: "Morocco", points: 10 },
  { category: "🔬 Science", question: "Which part of the human eye controls the amount of light entering it?", choices: ["Cornea", "Retina", "Iris", "Lens"], answer: "Iris", points: 10 },

];

// ── 🔥 HARD QUESTION POOL (100 questions, points: 20 each) ─────────────────
//    10 are randomly selected each game for the final difficult round.
const HARD_QUESTION_POOL = [
  // Science
  { category: "🔬 Science", question: "Which phenomenon occurs when the Moon passes between Earth and the Sun, blocking some or all of the Sun's light?", choices: ["Lunar eclipse", "Solar eclipse", "Solstice", "Equinox"], answer: "Solar eclipse", points: 20 },
  { category: "🔬 Science", question: "Which element has the atomic number 79?", choices: ["Silver", "Platinum", "Gold", "Mercury"], answer: "Gold", points: 20 },
  { category: "🔬 Science", question: "Which fundamental force is responsible for holding atomic nuclei together?", choices: ["Electromagnetic force", "Gravitational force", "Strong nuclear force", "Weak nuclear force"], answer: "Strong nuclear force", points: 20 },
  { category: "🔬 Science", question: "Which blood type is often described as the universal red-cell donor type?", choices: ["AB positive", "A positive", "O negative", "B negative"], answer: "O negative", points: 20 },
  { category: "🔬 Science", question: "Which geological process describes the movement of large sections of Earth's lithosphere?", choices: ["Erosion", "Plate tectonics", "Sedimentation", "Weathering"], answer: "Plate tectonics", points: 20 },
  { category: "🔬 Science", question: "Which scientific principle states that energy cannot be created or destroyed, only transformed from one form to another?", choices: ["Principle of relativity", "Law of conservation of energy", "Heisenberg uncertainty principle", "Archimedes' principle"], answer: "Law of conservation of energy", points: 20 },
  { category: "🔬 Science", question: "Which element has the chemical symbol Fe?", choices: ["Fluorine", "Iron", "Francium", "Fermium"], answer: "Iron", points: 20 },
  { category: "🔬 Science", question: "Which layer of Earth's atmosphere contains most of the ozone layer?", choices: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], answer: "Stratosphere", points: 20 },
  { category: "🔬 Science", question: "Which scientist formulated the three laws of planetary motion?", choices: ["Johannes Kepler", "Galileo Galilei", "Isaac Newton", "Nicolaus Copernicus"], answer: "Johannes Kepler", points: 20 },
  { category: "🔬 Science", question: "Which blood vessels generally carry blood away from the heart?", choices: ["Veins", "Arteries", "Capillaries", "Venules"], answer: "Arteries", points: 20 },
  { category: "🔬 Science", question: "What is the SI unit of electric resistance?", choices: ["Volt", "Watt", "Ampere", "Ohm"], answer: "Ohm", points: 20 },
  { category: "🔬 Science", question: "Which part of the brain is primarily associated with balance and coordination?", choices: ["Cerebellum", "Hypothalamus", "Medulla oblongata", "Amygdala"], answer: "Cerebellum", points: 20 },
  { category: "🔬 Science", question: "What is the name of the DNA structure described as a double helix?", choices: ["RNA", "ATP", "DNA double helix", "Ribosome"], answer: "DNA double helix", points: 20 },
  { category: "🔬 Science", question: "Which particle has no electric charge and is found in the nucleus of an atom?", choices: ["Proton", "Electron", "Neutron", "Photon"], answer: "Neutron", points: 20 },
  { category: "🔬 Science", question: "What is the name of the force that causes objects at rest to remain at rest?", choices: ["Gravity", "Inertia", "Friction", "Tension"], answer: "Inertia", points: 20 },
  { category: "🔬 Science", question: "Which type of electromagnetic radiation has the shortest wavelength?", choices: ["Radio waves", "Visible light", "X-rays", "Gamma rays"], answer: "Gamma rays", points: 20 },
  { category: "🔬 Science", question: "What is the term for the change of a gas directly into a solid without passing through the liquid state?", choices: ["Evaporation", "Condensation", "Sublimation", "Deposition"], answer: "Deposition", points: 20 },
  { category: "🔬 Science", question: "Which gas is produced when acids react with metals?", choices: ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], answer: "Hydrogen", points: 20 },
  { category: "🔬 Science", question: "What is the speed of light in a vacuum approximately equal to?", choices: ["100,000 km/s", "200,000 km/s", "300,000 km/s", "400,000 km/s"], answer: "300,000 km/s", points: 20 },
  { category: "🔬 Science", question: "Which organ in the human body is responsible for producing insulin?", choices: ["Liver", "Kidney", "Pancreas", "Adrenal gland"], answer: "Pancreas", points: 20 },
  { category: "🔬 Science", question: "What is the name of the unit used to measure the amount of a substance in chemistry?", choices: ["Gram", "Litre", "Mole", "Joule"], answer: "Mole", points: 20 },
  { category: "🔬 Science", question: "What is the chemical formula for table salt?", choices: ["KCl", "NaOH", "NaCl", "MgCl₂"], answer: "NaCl", points: 20 },
  { category: "🔬 Science", question: "Which planet has the Great Red Spot, a giant storm system?", choices: ["Saturn", "Mars", "Jupiter", "Neptune"], answer: "Jupiter", points: 20 },
  { category: "🔬 Science", question: "What is the name for the study of heredity and genetic variation?", choices: ["Ecology", "Genetics", "Microbiology", "Physiology"], answer: "Genetics", points: 20 },
  { category: "🔬 Science", question: "Which element is a liquid at room temperature and is also a metal?", choices: ["Bromine", "Mercury", "Gallium", "Cesium"], answer: "Mercury", points: 20 },
  { category: "🔬 Science", question: "What is the term for the bending of light as it passes from one medium to another?", choices: ["Reflection", "Diffraction", "Refraction", "Absorption"], answer: "Refraction", points: 20 },
  { category: "🔬 Science", question: "What is the name of the theory that describes the origin of the universe from an initial singularity?", choices: ["Steady State Theory", "Big Bang Theory", "String Theory", "Multiverse Theory"], answer: "Big Bang Theory", points: 20 },
  { category: "🔬 Science", question: "Which bone is commonly known as the collarbone?", choices: ["Sternum", "Clavicle", "Scapula", "Humerus"], answer: "Clavicle", points: 20 },
  { category: "🔬 Science", question: "What is the process by which bacteria convert atmospheric nitrogen into ammonia?", choices: ["Denitrification", "Nitrification", "Nitrogen fixation", "Ammonification"], answer: "Nitrogen fixation", points: 20 },
  { category: "🔬 Science", question: "Which part of the neuron receives signals from other neurons?", choices: ["Axon", "Dendrite", "Myelin sheath", "Synapse"], answer: "Dendrite", points: 20 },

  // History
  { category: "📚 History", question: "Which ancient civilization is credited with developing one of the earliest known alphabetic writing systems?", choices: ["Phoenicians", "Mongols", "Vikings", "Aztecs"], answer: "Phoenicians", points: 20 },
  { category: "📚 History", question: "Which civilization developed the writing system known as cuneiform?", choices: ["Sumerians", "Romans", "Vikings", "Aztecs"], answer: "Sumerians", points: 20 },
  { category: "📚 History", question: "Which ancient city was buried by the eruption of Mount Vesuvius in 79 CE?", choices: ["Pompeii", "Athens", "Carthage", "Alexandria"], answer: "Pompeii", points: 20 },
  { category: "📚 History", question: "Which treaty is commonly associated with formally ending the First World War between Germany and the Allied Powers?", choices: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Vienna", "Treaty of Utrecht"], answer: "Treaty of Versailles", points: 20 },
  { category: "📚 History", question: "Who was the first Emperor of a unified China?", choices: ["Kublai Khan", "Qin Shi Huang", "Liu Bang", "Yongle Emperor"], answer: "Qin Shi Huang", points: 20 },
  { category: "📚 History", question: "Which country was the first to industrialize during the Industrial Revolution?", choices: ["France", "Germany", "United States", "United Kingdom"], answer: "United Kingdom", points: 20 },
  { category: "📚 History", question: "Which event in 1789 marked the beginning of the French Revolution?", choices: ["Execution of Louis XVI", "Storming of the Bastille", "Declaration of the Rights of Man", "The Tennis Court Oath"], answer: "Storming of the Bastille", points: 20 },
  { category: "📚 History", question: "Who was the leader of the Soviet Union during the Cuban Missile Crisis?", choices: ["Joseph Stalin", "Leonid Brezhnev", "Nikita Khrushchev", "Mikhail Gorbachev"], answer: "Nikita Khrushchev", points: 20 },
  { category: "📚 History", question: "Which Roman general crossed the Rubicon river in 49 BC, triggering a civil war?", choices: ["Pompey", "Julius Caesar", "Mark Antony", "Augustus"], answer: "Julius Caesar", points: 20 },
  { category: "📚 History", question: "The Meiji Restoration of 1868 was a pivotal event in which country's history?", choices: ["China", "Korea", "Japan", "Vietnam"], answer: "Japan", points: 20 },
  { category: "📚 History", question: "Who was the first person to circumnavigate the globe?", choices: ["Vasco da Gama", "Christopher Columbus", "James Cook", "Ferdinand Magellan"], answer: "Ferdinand Magellan", points: 20 },
  { category: "📚 History", question: "Which empire was ruled by Suleiman the Magnificent?", choices: ["Persian Empire", "Ottoman Empire", "Mongol Empire", "Byzantine Empire"], answer: "Ottoman Empire", points: 20 },
  { category: "📚 History", question: "In which year did the Russian Revolution take place?", choices: ["1905", "1914", "1917", "1921"], answer: "1917", points: 20 },
  { category: "📚 History", question: "Which battle in 1815 marked Napoleon Bonaparte's final defeat?", choices: ["Battle of Austerlitz", "Battle of Trafalgar", "Battle of Waterloo", "Battle of Leipzig"], answer: "Battle of Waterloo", points: 20 },
  { category: "📚 History", question: "Which African leader was the first President of an independent Ghana?", choices: ["Nelson Mandela", "Kwame Nkrumah", "Julius Nyerere", "Jomo Kenyatta"], answer: "Kwame Nkrumah", points: 20 },

  // Math
  { category: "🔢 Math", question: "Which of these numbers is irrational?", choices: ["0.5", "3/4", "√2", "2"], answer: "√2", points: 20 },
  { category: "🔢 Math", question: "What is the smallest prime number?", choices: ["0", "1", "2", "3"], answer: "2", points: 20 },
  { category: "🔢 Math", question: "What is the value of log₁₀(1000)?", choices: ["2", "3", "4", "10"], answer: "3", points: 20 },
  { category: "🔢 Math", question: "How many degrees does the interior of a regular hexagon contain in total?", choices: ["540°", "720°", "900°", "1080°"], answer: "720°", points: 20 },
  { category: "🔢 Math", question: "What is the derivative of sin(x)?", choices: ["cos(x)", "-cos(x)", "tan(x)", "-sin(x)"], answer: "cos(x)", points: 20 },
  { category: "🔢 Math", question: "What is the formula for the volume of a sphere?", choices: ["(4/3)πr³", "πr²h", "(2/3)πr³", "4πr²"], answer: "(4/3)πr³", points: 20 },
  { category: "🔢 Math", question: "If a function f(x) = 3x² + 2x − 5, what is f(2)?", choices: ["9", "11", "13", "15"], answer: "11", points: 20 },
  { category: "🔢 Math", question: "What is the sum of all interior angles of a pentagon?", choices: ["360°", "450°", "540°", "720°"], answer: "540°", points: 20 },
  { category: "🔢 Math", question: "Which number is both a perfect square and a perfect cube?", choices: ["8", "27", "64", "16"], answer: "64", points: 20 },
  { category: "🔢 Math", question: "What is Euler's number (e) approximately equal to?", choices: ["2.14", "2.72", "3.14", "1.62"], answer: "2.72", points: 20 },
  { category: "🔢 Math", question: "In a right triangle, if one angle is 30° and the hypotenuse is 10, what is the length of the side opposite the 30° angle?", choices: ["3", "5", "7", "8"], answer: "5", points: 20 },
  { category: "🔢 Math", question: "What is the 10th term of the Fibonacci sequence (starting 1, 1, 2, 3, 5, …)?", choices: ["34", "55", "89", "44"], answer: "55", points: 20 },
  { category: "🔢 Math", question: "What is the probability of rolling two sixes in a row on a standard die?", choices: ["1/12", "1/36", "1/18", "1/6"], answer: "1/36", points: 20 },

  // Language
  { category: "📖 Language", question: "What is the term for a word that has the opposite meaning of another word?", choices: ["Synonym", "Homonym", "Antonym", "Acronym"], answer: "Antonym", points: 20 },
  { category: "📖 Language", question: "Which of these languages belongs to the Romance language family?", choices: ["German", "Portuguese", "Arabic", "Japanese"], answer: "Portuguese", points: 20 },
  { category: "📖 Language", question: "What is the grammatical term for the subject of a passive sentence?", choices: ["Direct object", "Indirect object", "Agent", "Predicate"], answer: "Agent", points: 20 },
  { category: "📖 Language", question: "What literary device is used when a writer gives human qualities to non-human things?", choices: ["Metaphor", "Simile", "Personification", "Irony"], answer: "Personification", points: 20 },
  { category: "📖 Language", question: "Which of these is an example of dramatic irony?", choices: ["A character trips on a banana peel.", "The audience knows the villain is hiding behind the door, but the hero does not.", "A storm reflects a character's anger.", "A character says they are fine when they are not."], answer: "The audience knows the villain is hiding behind the door, but the hero does not.", points: 20 },
  { category: "📖 Language", question: "What is the term for a narrative technique where the story is told by a character within the story?", choices: ["Third-person omniscient", "First-person narrative", "Stream of consciousness", "Free indirect discourse"], answer: "First-person narrative", points: 20 },
  { category: "📖 Language", question: "What is the name for the repetition of a word or phrase at the beginning of successive clauses?", choices: ["Epistrophe", "Chiasmus", "Anaphora", "Zeugma"], answer: "Anaphora", points: 20 },
  { category: "📖 Language", question: "Which grammatical mood is used to express wishes, hypotheticals, or doubts?", choices: ["Indicative", "Imperative", "Subjunctive", "Conditional"], answer: "Subjunctive", points: 20 },
  { category: "📖 Language", question: "What is a portmanteau word?", choices: ["A word with multiple meanings", "A word blending two other words", "A borrowed word from another language", "A word that has become obsolete"], answer: "A word blending two other words", points: 20 },
  { category: "📖 Language", question: "What is the term for using a part to represent the whole, such as 'all hands on deck'?", choices: ["Metonymy", "Synecdoche", "Euphemism", "Hyperbole"], answer: "Synecdoche", points: 20 },

  // Art & Culture
  { category: "🎨 Art & Culture", question: "Which philosopher wrote The Republic?", choices: ["Aristotle", "Socrates", "Plato", "Epicurus"], answer: "Plato", points: 20 },
  { category: "🎨 Art & Culture", question: "What artistic movement was Salvador Dalí associated with?", choices: ["Cubism", "Surrealism", "Impressionism", "Futurism"], answer: "Surrealism", points: 20 },
  { category: "🎨 Art & Culture", question: "Which novel by Franz Kafka tells the story of a man who wakes up transformed into a giant insect?", choices: ["The Trial", "Amerika", "The Metamorphosis", "The Castle"], answer: "The Metamorphosis", points: 20 },
  { category: "🎨 Art & Culture", question: "Who composed the opera 'La Traviata'?", choices: ["Puccini", "Verdi", "Mozart", "Wagner"], answer: "Verdi", points: 20 },
  { category: "🎨 Art & Culture", question: "Which ancient Greek tragedy was written by Sophocles and features the character Oedipus?", choices: ["Medea", "Antigone", "Oedipus Rex", "The Oresteia"], answer: "Oedipus Rex", points: 20 },
  { category: "🎨 Art & Culture", question: "In which city is the Uffizi Gallery, home to Botticelli's 'The Birth of Venus', located?", choices: ["Rome", "Venice", "Florence", "Milan"], answer: "Florence", points: 20 },
  { category: "🎨 Art & Culture", question: "Which author wrote the novel 'One Hundred Years of Solitude'?", choices: ["Mario Vargas Llosa", "Jorge Luis Borges", "Gabriel García Márquez", "Pablo Neruda"], answer: "Gabriel García Márquez", points: 20 },
  { category: "🎨 Art & Culture", question: "What is the name of the narrative technique used in James Joyce's 'Ulysses' that mimics the flow of thoughts?", choices: ["Free verse", "Stream of consciousness", "Magic realism", "Epistolary"], answer: "Stream of consciousness", points: 20 },
  { category: "🎨 Art & Culture", question: "Which Renaissance artist painted the ceiling of the Sistine Chapel?", choices: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Donatello"], answer: "Michelangelo", points: 20 },
  { category: "🎨 Art & Culture", question: "What musical term describes a gradual increase in tempo?", choices: ["Ritardando", "Accelerando", "Crescendo", "Diminuendo"], answer: "Accelerando", points: 20 },

  // Geography
  { category: "🌍 Geography", question: "What is the name of the tectonic plate boundary where plates move apart from each other?", choices: ["Convergent boundary", "Transform boundary", "Divergent boundary", "Subduction zone"], answer: "Divergent boundary", points: 20 },
  { category: "🌍 Geography", question: "Which country contains more than 17,000 islands?", choices: ["Philippines", "Japan", "Indonesia", "Malaysia"], answer: "Indonesia", points: 20 },
  { category: "🌍 Geography", question: "What is the name of the boundary between the troposphere and stratosphere?", choices: ["Mesopause", "Tropopause", "Stratopause", "Thermopause"], answer: "Tropopause", points: 20 },
  { category: "🌍 Geography", question: "Which country is home to the world's largest salt flat, Salar de Uyuni?", choices: ["Argentina", "Chile", "Bolivia", "Peru"], answer: "Bolivia", points: 20 },
  { category: "🌍 Geography", question: "In which ocean is the island of Madagascar located?", choices: ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Southern Ocean"], answer: "Indian Ocean", points: 20 },
  { category: "🌍 Geography", question: "Which mountain range contains the highest peak in North America?", choices: ["Rocky Mountains", "Sierra Nevada", "Appalachians", "Alaska Range"], answer: "Alaska Range", points: 20 },
  { category: "🌍 Geography", question: "What is the term for a narrow strip of land connecting two larger land masses?", choices: ["Peninsula", "Isthmus", "Cape", "Archipelago"], answer: "Isthmus", points: 20 },
  { category: "🌍 Geography", question: "Which river is the primary source of water for ancient Egyptian civilization?", choices: ["Tigris", "Euphrates", "Nile", "Congo"], answer: "Nile", points: 20 },
  { category: "🌍 Geography", question: "Which sea has the highest salinity of any major body of water?", choices: ["Mediterranean Sea", "Red Sea", "Dead Sea", "Caspian Sea"], answer: "Dead Sea", points: 20 },
  { category: "🌍 Geography", question: "What is the name of the biogeographic region that includes Australia, New Zealand, and nearby islands?", choices: ["Nearctic", "Palearctic", "Australasia", "Afrotropic"], answer: "Australasia", points: 20 },

  // Nature
  { category: "🍎 Nature", question: "What is the term for animals that are active mainly during the night?", choices: ["Aquatic", "Nocturnal", "Diurnal", "Arboreal"], answer: "Nocturnal", points: 20 },
  { category: "🍎 Nature", question: "What is the name of the symbiotic relationship where both species benefit?", choices: ["Parasitism", "Commensalism", "Mutualism", "Predation"], answer: "Mutualism", points: 20 },
  { category: "🍎 Nature", question: "What is the largest organ of the human body?", choices: ["Liver", "Lung", "Skin", "Brain"], answer: "Skin", points: 20 },
  { category: "🍎 Nature", question: "What is the name of the process by which RNA is used to make a protein?", choices: ["Transcription", "Replication", "Translation", "Mutation"], answer: "Translation", points: 20 },
  { category: "🍎 Nature", question: "Which animal has the highest blood pressure of any land animal?", choices: ["Elephant", "Giraffe", "Blue whale", "Cheetah"], answer: "Giraffe", points: 20 },
  { category: "🍎 Nature", question: "What is the name of the ecological concept describing the role of a species in its environment?", choices: ["Habitat", "Niche", "Biome", "Ecosystem"], answer: "Niche", points: 20 },
  { category: "🍎 Nature", question: "Which type of rock is formed by the alteration of existing rocks due to heat and pressure?", choices: ["Igneous", "Sedimentary", "Metamorphic", "Volcanic"], answer: "Metamorphic", points: 20 },
  { category: "🍎 Nature", question: "What is the name for the outermost layer of Earth?", choices: ["Mantle", "Core", "Crust", "Lithosphere"], answer: "Crust", points: 20 },
  { category: "🍎 Nature", question: "Which biome is characterized by the highest biodiversity on Earth?", choices: ["Savanna", "Taiga", "Tropical rainforest", "Temperate forest"], answer: "Tropical rainforest", points: 20 },
  { category: "🍎 Nature", question: "What is the correct term for a group of lions?", choices: ["Pack", "Herd", "Pride", "Colony"], answer: "Pride", points: 20 }
];
